#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1530894697                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Scale your recipes with ease.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Meng Kuong Lei                                
your_link                                 : https://supernova1027.blogspot.com                    
your_city                                 : Macau, China                                
email_address                             : csl.supernova@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : cslsupernova
github_username                           : cslsupernova
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Change Number of Serves
    description                           : One button clicks to change the number of serves in recipe.
    fontawesome_icon_name                 : play-circle
    
  - title                                 : Adjust Ingredients Quantities
    description                           : Instantly show all adjusted ingredients quantities in recipe
    fontawesome_icon_name                 : magic

  - title                                 : Recipe Details with Photo, etc.
    description                           : Store recipes with Photo, Rating, Easiness, etc.
    fontawesome_icon_name                 : play-circle

  - title                                 : Ingredient Units
    description                           : Ingredient supports standard metric units (US units will be supported in future release).
    fontawesome_icon_name                 : sync

  - title                                 : Other Features
    description                           : Dark Mode support. Optimized for iPhone 11 and SE2
    fontawesome_icon_name                 : star
  
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.1
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
